name: cate-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6*
  #
  # dependencies (in alphabetical order)
  #
  - attrs >=18.2.0
  - boto3 >=1.9.2,<2.0
  - botocore >=1.12.3,<2.0
  - cartopy >=0.15,<1.0
  - conda >=4.5.1,<5.0
  # Include Cython, otherwise pip will do so during "python setup.py install" (why???)
  - cython >=0.25,<1.0
  - dask >=0.19,<1.0.3
  - fiona >=1.7,<2.0
  - gdal >=2.2.3,<3.0
  - geopandas >=0.3,<1.0
  # require specific minor version to prevent downgrade
  - geos >=3.5.1,<4.0
  # require specific minor version to prevent downgrade
  - hdf4 >=4.2.12,<5.0
  - h5netcdf >=0.4.2,<1.0
  - jdcal >=1.3,<2.0
  - matplotlib >=2.2,<3.0
  # munch 2.3.2 caused a build error in Windows with error message:
  # error: [WinError 32] The process cannot access the file because it is being used by another process:
  - munch ==2.3.1
  - netcdf4 >=1.2,<2.0
  - numba >=0.33,<1.0
  # Starting from numpy 1.13 xarray ufuncs are deprecated, as np ufuncs work across dask datasets
  - numpy >=1.13,<2.0
  - owslib >=0.14,<1.0
  - pandas >=0.22,<1.0
  - pillow >=5.0,<6.0
  - psutil >=5.2,<6.0
  - pyproj >=1.9,<2.0
  - pyqt >=5.6,<6.0
  - pyshp >=1.2,<2.0
  - python-dateutil >=2.6,<3.0
  - scipy >=0.19,<1.0
  - shapely >=1.6,<2.0
  - tornado >=5.0,<6.0
  - xarray >=0.10.6
  #
  # for testing only
  #
  - pytest >=3.1,<3.2
  - pytest-cov >=2.5.1,<2.6
  - flake8

